@startuml
start
:Пользователь открывает приложение "Простое меню";
:Пользователь вводит список доступных продуктов;
if (Есть ли рецепты?) then (да)
  :Приложение выполняет поиск рецептов;
else (нет)
  :Приложение сообщает об отсутствии рецептов;
endif
:Приложение предоставляет список рецептов, соответствующих доступным продуктам;
:Пользователь просматривает рецепты и выбирает подходящий для ужина;
stop
@enduml