@startuml

|Пользователь (Елена)|
start
:Открывает приложение "Простое меню";
:Ищет рецепты на основе доступных продуктов или предпочтений;
:Предоставляет быстрый доступ к рецептам;
if (Пользователь выбирает рецепт?) then (yes)
  :Добавляет рецепт в список планируемых блюд;
else (no)
  if (Пользователь хочет составить меню на основе избранных рецептов?) then (yes)
    :Составляет меню на основе рецептов из списка избранных;
  endif
endif
stop

@enduml