@startuml

actor "Пользователь (Елена)" as Elena
participant "Простое меню" as Menu
participant "База данных рецептов" as DB

Elena -> Menu : Открывает приложение "Простое меню"
Elena -> Menu : Ищет рецепты на основе доступных продуктов или предпочтений
Menu -> DB : Запрос рецептов
DB --> Menu : Ответ с рецептами
Menu -> Elena : Предоставляет быстрый доступ к рецептам

alt Пользователь выбирает рецепт
  Elena -> Menu : Добавляет рецепт в список планируемых блюд
else Пользователь хочет составить меню на основе избранных рецептов
  Elena -> Menu : Составляет меню на основе рецептов из списка избранных
end

@enduml