@startuml
start
:Пользователь открывает приложение "Простое меню";
:Пользователь просматривает раздел с питательными и вкусными блюдами;
if (Есть ли рецепты?) then (да)
  :Приложение предоставляет список рецептов, отвечающих критериям;
else (нет)
  :Приложение предлагает поиск альтернативных вариантов или уведомляет о недоступности;
endif
:Пользователь выбирает подходящий рецепт для приготовления;
stop
@enduml