@startuml

actor "Пользователь (Елена)" as Elena
participant "Простое меню" as Menu
participant "База данных пользователей" as DB

Elena -> Menu : Открывает приложение "Простое меню"
Elena -> Menu : Выбирает опцию "Зарегистрироваться" и вводит данные
Menu -> DB : Создает учетную запись пользователя
DB --> Menu : Подтверждение создания учетной записи
Menu --> Elena : Возвращается в приложение

@enduml