@startuml

|Пользователь (Елена)|
start
:Открывает приложение "Простое меню";
if (Пользователь зарегистрирован?) then (да)
  :Входит в свою учетную запись;
  stop
else (нет)
  :Выбирает опцию "Зарегистрироваться" и вводит данные;
  :Приложение создает учетную запись пользователя;
  stop
endif

@enduml