@startuml



actor "Пользователь (Елена)" as Elena
actor "Простое меню" as Menu
actor "База данных рецептов" as DB
rectangle {
Elena --> (Использование приложения "Простое меню")

(Использование приложения "Простое меню") --> (Поиск рецептов на основе доступных продуктов)
(Использование приложения "Простое меню") --> (Регистрация пользователя)

(Поиск рецептов на основе доступных продуктов) --> Menu
(Регистрация пользователя) --> Menu
Menu --> DB : Запрос рецептов
DB --> Menu : Ответ с рецептами
Menu --> Elena : Предоставление рецептов
}
@enduml